package negocio.entidades.bolsa;

public enum ModalidadePagamento {
    TUTOR,
    COORDENADORIA_DE_POLO,
    COORDENADORIA_ADJUNTA,
    COORDENADORIA_DE_CURSO_I,
    COORDENADORIA_DE_CURSO_II,
    COORDENADOR_DE_TUTORIA,
    COORDENADORIA_DE_TUTORIA_I,
    COORDENADORIA_DE_TUTORIA_II,
    COORDENADORIA_DE_GERAL,
    PROFESSOR_FORMADOR_I,
    PROFESSOR_FORMADOR_II,
    PROFESSOR_CONTEUDISTA_I,
    PROFESSOR_CONTEUDISTA_II,
}
